version: '3.8'
services:
  movies:
    image: raghava1826/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: raghava1826/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: raghava1826/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: raghava1826/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
